
services:
  jenkins-agent:
    # Build the image from the custom Dockerfile named Dockerfile.agent
    build:
      context: .

    # Set the container name
    container_name: jenkins-agent

    # Environment variables required for the agent to connect to Jenkins master
    environment:
      # URL of the Jenkins master (adjust host if not on the same machine)
      - JENKINS_URL=http://host.docker.internal:8080/

      # Work directory inside the container for the agent
      - JENKINS_AGENT_WORKDIR=/home/jenkins/agent

      # Secret/token generated when creating the agent on Jenkins master
      - JENKINS_SECRET=your-agent-secret

      # Name of the agent (must match what you configured on the master)
      - JENKINS_NAME=agent-01

    # Mount Docker socket to allow this agent to run Docker commands on the host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    # Restart the container automatically unless explicitly stopped
    restart: unless-stopped


# Jenkins inside the container runs on port 8080
# Your host (Ubuntu) exposes port 8085 to the outside world (your browser, etc.)
# So when you go to http://localhost:8085, Docker forwards the traffic to Jenkins inside the container on port 8080
# Why use a different host port?
# Because your native Jenkins install on Ubuntu already uses 8080 — so you can't use the same port for both. Ports on the host must be unique.
# If you tried to use - "8080:8080" for the Docker container, it would conflict with the native Jenkins running on your machine.
