# Define the version of the Docker Compose file format
# version: '3.8'

services:
  # Define the Jenkins service
  jenkins:
    build: .
    container_name: jenkins     # Name the container 'jenkins' for easier reference
    ports:
      - "8085:8080"             # Expose Jenkins on the Container "8080" to the host web interface on localhost:8085
      - "50000:50000"           # Port for Jenkins agents to connect (used for distributed builds)
    volumes:
      - jenkins_data:/var/jenkins_home  # Persist Jenkins home directory (job configs, plugins, etc.)
      - /var/run/docker.sock:/var/run/docker.sock  # Allow Jenkins to communicate with host Docker daemon
    user: root  # To avoid permission issues when Jenkins interacts with host

# Define named volumes (for data persistence)
volumes:
  jenkins_data:  # Named volume to persist Jenkins data across container restarts
